<script setup lang="ts">
const route = useRoute();
console.log("Current route path:", route.path);
</script>

<template>
  <div class="bg-neutral-100">
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
    <div>Okay</div>
  </div>
</template>

<style scoped></style>
